import React from 'react';
import { Cloud, LogIn, LogOut, RefreshCw, Trash2 } from 'lucide-react';
import type { SyncState } from '../../types/sync';
export const AccountSyncCard:React.FC<{user:{email?:string;name?:string;authProvider?:string}|null;sync:SyncState;onLogin:()=>void;onGoogleLogin:()=>void;onLogout:()=>void;onDeleteAccount:()=>void;onSync:()=>void}>=({user,sync,onLogin,onGoogleLogin,onLogout,onDeleteAccount,onSync})=><div className="p-5 rounded-3xl bg-white dark:bg-stone-900 border border-stone-200 dark:border-stone-800 space-y-3">
  <div className="flex items-center justify-between gap-3"><div><div className="text-sm font-bold flex items-center gap-2"><Cloud className="w-4 h-4 text-amber-600"/>Tài khoản & đồng bộ đa thiết bị</div><div className="text-xs text-stone-500 mt-1">{user?user.email:'Đang dùng học tập cục bộ trên thiết bị này.'}</div></div>
  {user?<button onClick={onLogout} className="px-3 py-2 rounded-xl bg-stone-100 dark:bg-stone-800 text-xs font-semibold flex items-center gap-1"><LogOut className="w-3.5 h-3.5"/>Đăng xuất</button>:<div className="flex items-center gap-1.5"><button onClick={onGoogleLogin} className="px-3 py-2 rounded-xl border border-stone-200 dark:border-stone-700 bg-white dark:bg-stone-900 text-stone-800 dark:text-stone-100 text-xs font-semibold">Tiếp tục với Google</button><button onClick={onLogin} className="px-3 py-2 rounded-xl bg-stone-900 text-white dark:bg-stone-100 dark:text-stone-900 text-xs font-semibold flex items-center gap-1"><LogIn className="w-3.5 h-3.5"/>Đăng nhập</button></div>}
  {user&&<div className="flex items-center justify-between gap-2 pt-1"><span className="text-[11px] text-stone-400">{user.authProvider==='google'?'Đăng nhập bằng Google':'Tài khoản cá nhân'}</span><button onClick={onDeleteAccount} className="text-[11px] text-rose-600 hover:underline flex items-center gap-1"><Trash2 className="w-3 h-3"/>Xóa tài khoản</button></div>}</div>
  <div className="flex items-center justify-between text-xs"><span>{sync.status==='synced'?'✓ Đã đồng bộ':sync.status==='syncing'?'↻ Đang đồng bộ':sync.status==='offline'?'○ Ngoại tuyến':'! Đồng bộ lỗi'}</span><button onClick={onSync} disabled={!user||sync.status==='syncing'} className="flex items-center gap-1 px-2.5 py-1.5 rounded-lg bg-stone-100 dark:bg-stone-800 disabled:opacity-50"><RefreshCw className="w-3 h-3"/>Đồng bộ</button></div>
  {sync.lastSyncedAt&&<div className="text-[11px] text-stone-400">Lần cuối: {new Date(sync.lastSyncedAt).toLocaleString('vi-VN')}</div>}
  {sync.pendingCount>0&&<div className="text-[11px] text-amber-600">{sync.pendingCount} thay đổi đang chờ đồng bộ.</div>}
  {sync.error&&<div className="text-[11px] text-rose-600">{sync.error}</div>}
</div>;