import assert from 'node:assert/strict';
import fs from 'node:fs';
const read=(p:string)=>fs.readFileSync(p,'utf8');
const outfit=read('src/services/linaAvatarConfig.ts');
const eyes=read('src/services/eyeContactController.ts');
const lip=read('src/services/lipSyncEngine.ts');
const tts=read('src/services/streamingTTS.ts');
const queue=read('src/services/ttsQueue.ts');
const orch=read('src/services/realtimeSpeechOrchestrator.ts');
const avatar=read('src/services/avatarService.ts');
const anim=read('src/services/avatarAnimationEngine.ts');
assert.match(outfit,/dusty-rose-pink/);
assert.match(outfit,/ribbed-knit-top/);
assert.match(outfit,/scoop/);
assert.match(outfit,/dark short bob/);
assert.match(eyes,/nextBlinkAt/);
assert.match(eyes,/mode(?:\s*)={3}(?:'THINKING'|\"THINKING\")/);
assert.match(lip,/metrics.isSpeaking/);
assert.match(lip,/this.smoothed/);
assert.match(lip,/jaw/);
assert.match(tts,/state==='playing'/);
assert.match(tts,/playWithRealAudioStart/);
assert.match(queue,/turnId/);
assert.match(queue,/sentence_/);
assert.match(orch,/startsWith/);
assert.match(avatar,/resetAvatarState/);
assert.match(avatar,/audioStreamController.subscribe/);
assert.match(anim,/eyeContactController/);
assert.doesNotMatch(eyes, /\?\.[0-9]/);
assert.doesNotMatch(anim, /\?\.[0-9]/);
console.log('Prompt 34 avatar consistency, audio sync, interruption and race-guard tests passed.');