import assert from 'node:assert/strict';
import { buildKnowledgeProfile, generateDailyPlan, getAdaptiveDifficulty, resetPersonalizationSkill } from '../src/services/personalization';
import type { AIStoredMemory, LearnerProfile } from '../src/types/learning';

const profile={id:'u',displayName:'Lina learner',nativeLanguage:'vi',targetLanguage:'zh-CN',currentLevel:'beginner',hskLevel:'HSK 1',pinyinLevel:'marks',learningGoal:'conversation',dailyGoalMinutes:10,streak:1,totalStudyMinutes:20,vocabularyStats:{learned:10,mastered:2,weak:2},grammarStats:{learned:2,weak:1},pronunciationStats:{accuracy:60,weakTones:['3-3']},speakingStats:{practiceCount:2,accuracy:55},listeningStats:{practiceCount:2,accuracy:50},readingStats:{practiceCount:1,accuracy:60},writingStats:{practiceCount:0,accuracy:0},weakAreas:['了'],strongAreas:[],recentLessons:[],recentMistakes:['了'],preferredTopics:['family'],lastActiveAt:new Date().toISOString()} as unknown as LearnerProfile;
const memory:AIStoredMemory={learnerFacts:[],learningHistory:[],mistakes:[{id:'m1',type:'grammar',original:'了',corrected:'过',explanation:'x',severity:'high',frequency:3,firstSeen:new Date().toISOString(),lastSeen:new Date().toISOString(),resolved:false,mastery:10}],masteredVocabulary:[],weakVocabulary:['买'],grammarWeaknesses:['了'],pronunciationWeaknesses:['3-3'],conversationSummary:'',goals:[],preferences:['family'],topics:[],lastConversationAt:null};
const schedules={a:{mastery:30,correctCount:1,incorrectCount:3,lastReviewed:new Date().toISOString(),nextReview:new Date(Date.now()-1000).toISOString()},b:{mastery:90,correctCount:8,incorrectCount:1,lastReviewed:new Date().toISOString(),nextReview:new Date(Date.now()+86400000).toISOString()}};
const knowledge=buildKnowledgeProfile(profile,memory,schedules,{lesson:{mastery:40,speaking:30,listening:20,grammar:35}});
assert.equal(knowledge.dueReviewCount,1);
assert.equal(knowledge.vocabulary.length,2);
assert.equal(knowledge.adaptiveDifficulty.level,'support');
assert.ok(knowledge.strugglingAreas.length>0);
const plan=generateDailyPlan(profile,memory,knowledge.dueReviewCount,knowledge);
assert.ok(plan.items.length>=3);
assert.ok(plan.items.some(x=>x.reason.includes('Lina đề xuất vì')));
assert.equal(getAdaptiveDifficulty(profile,memory,knowledge).pinyin,'always');
const reset=resetPersonalizationSkill(memory,'grammar');
assert.deepEqual(reset.grammarWeaknesses,[]);
assert.equal(reset.mistakes.length,1);
console.log('Prompt 24 personalization checks passed.');
